// Code generated by errxgen; DO NOT EDIT.

package example

import "fmt"

func (e *DeniedError) Error() string {
	return fmt.Sprintf("open %s: permission denied (uid %d)", e.Path, e.UID)
}

func (e *DeniedError) Code() string { return "IO_DENIED" }

func (e *DeniedError) Unwrap() error { return e.Err }

func (e *MissingKeyError) Error() string {
	return fmt.Sprintf("config key %q is required", e.Key)
}

func (e *MissingKeyError) Code() string { return "CONFIG_MISSING" }
