// Package example demonstrates errxgen. Run `go generate ./...` to (re)emit
// example_errxgen.go from the directives below.
package example

//go:generate go run github.com/ubgo/errx/cmd/errxgen .

// DeniedError reports a filesystem permission failure. Its Error/Code/
// Unwrap methods are generated by errxgen from the directive below.
//
// errxgen: message="open %s: permission denied (uid %d)" args=Path,UID code=IO_DENIED unwrap=Err
type DeniedError struct {
	Path string
	UID  int
	Err  error
}

// MissingKeyError reports a required configuration key that was absent.
// Its Error/Code methods are generated by errxgen from the directive below.
//
// errxgen: message="config key %q is required" args=Key code=CONFIG_MISSING
type MissingKeyError struct {
	Key string
}
