// Command errxgen generates error boilerplate from a declarative directive,
// closing Go's biggest ergonomic gap vs Rust's thiserror (Go has no derive
// macros). Annotate a struct with a doc directive:
//
//	//errxgen: message="open %s: permission denied" args=Path code=IO_DENIED unwrap=Err
//	type DeniedError struct {
//		Path string
//		Err  error
//	}
//
// then `//go:generate errxgen` (or `go run github.com/ubgo/errx/cmd/errxgen`)
// emits <file>_errxgen.go with Error(), Unwrap() and Code() so the type is
// a complete, matchable error with zero hand-written boilerplate.
//
// The generated code imports only "fmt" (no errx dependency), so generated
// types stay usable anywhere.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const directive = "errxgen:"

type spec struct {
	TypeName string
	Message  string
	Args     []string
	Code     string
	Unwrap   string
}

func main() {
	dir := "."
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}
	if err := run(dir); err != nil {
		fmt.Fprintln(os.Stderr, "errxgen:", err)
		os.Exit(1)
	}
}

func run(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_errxgen.go") &&
			!strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return err
	}
	for _, pkg := range pkgs {
		for fname, file := range pkg.Files {
			specs := collect(file)
			if len(specs) == 0 {
				continue
			}
			out := generate(pkg.Name, specs)
			target := strings.TrimSuffix(fname, ".go") + "_errxgen.go"
			formatted, ferr := format.Source(out)
			if ferr != nil {
				return fmt.Errorf("%s: generated code invalid: %w", filepath.Base(target), ferr)
			}
			if werr := os.WriteFile(target, formatted, 0o644); werr != nil {
				return werr
			}
			fmt.Println("errxgen: wrote", filepath.Base(target))
		}
	}
	return nil
}

func collect(file *ast.File) []spec {
	var specs []spec
	for _, decl := range file.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		doc := gd.Doc
		for _, ts := range gd.Specs {
			t, ok := ts.(*ast.TypeSpec)
			if !ok {
				continue
			}
			if _, ok := t.Type.(*ast.StructType); !ok {
				continue
			}
			d := doc
			if t.Doc != nil {
				d = t.Doc
			}
			if d == nil {
				continue
			}
			if s, ok := parseDirective(d, t.Name.Name); ok {
				specs = append(specs, s)
			}
		}
	}
	return specs
}

func parseDirective(doc *ast.CommentGroup, typeName string) (spec, bool) {
	for _, c := range doc.List {
		line := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if !strings.HasPrefix(line, directive) {
			continue
		}
		s := spec{TypeName: typeName}
		for k, v := range parseKV(strings.TrimSpace(line[len(directive):])) {
			switch k {
			case "message":
				s.Message = v
			case "args":
				if v != "" {
					s.Args = strings.Split(v, ",")
				}
			case "code":
				s.Code = v
			case "unwrap":
				s.Unwrap = v
			}
		}
		if s.Message == "" {
			s.Message = typeName
		}
		return s, true
	}
	return spec{}, false
}

// parseKV parses `a="x y" b=z` into a map, honoring double quotes.
func parseKV(s string) map[string]string {
	m := map[string]string{}
	i := 0
	for i < len(s) {
		for i < len(s) && s[i] == ' ' {
			i++
		}
		eq := strings.IndexByte(s[i:], '=')
		if eq < 0 {
			break
		}
		key := strings.TrimSpace(s[i : i+eq])
		i += eq + 1
		var val string
		if i < len(s) && s[i] == '"' {
			i++
			start := i
			for i < len(s) && s[i] != '"' {
				i++
			}
			val = s[start:i]
			if i < len(s) {
				i++
			}
		} else {
			start := i
			for i < len(s) && s[i] != ' ' {
				i++
			}
			val = s[start:i]
		}
		m[key] = val
	}
	return m
}

func generate(pkg string, specs []spec) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by errxgen; DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintln(&b, `import "fmt"`)
	for _, s := range specs {
		recv := "e"
		fmt.Fprintf(&b, "\nfunc (%s *%s) Error() string {\n", recv, s.TypeName)
		if len(s.Args) == 0 {
			fmt.Fprintf(&b, "\treturn %s\n}\n", strconv.Quote(s.Message))
		} else {
			args := make([]string, len(s.Args))
			for i, a := range s.Args {
				args[i] = recv + "." + strings.TrimSpace(a)
			}
			fmt.Fprintf(&b, "\treturn fmt.Sprintf(%s, %s)\n}\n",
				strconv.Quote(s.Message), strings.Join(args, ", "))
		}
		if s.Code != "" {
			fmt.Fprintf(&b, "\nfunc (%s *%s) Code() string { return %s }\n",
				recv, s.TypeName, strconv.Quote(s.Code))
		}
		if s.Unwrap != "" {
			fmt.Fprintf(&b, "\nfunc (%s *%s) Unwrap() error { return %s.%s }\n",
				recv, s.TypeName, recv, s.Unwrap)
		}
	}
	return b.Bytes()
}
