package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseKV(t *testing.T) {
	m := parseKV(`message="open %s: denied" args=Path,UID code=IO unwrap=Err`)
	if m["message"] != "open %s: denied" {
		t.Fatalf("message = %q", m["message"])
	}
	if m["args"] != "Path,UID" || m["code"] != "IO" || m["unwrap"] != "Err" {
		t.Fatalf("kv = %+v", m)
	}
}

func TestRunGeneratesCompilableCode(t *testing.T) {
	dir := t.TempDir()
	src := `package demo

//errxgen: message="bad token %q at %d" args=Tok,Pos code=LEX unwrap=Err
type LexError struct {
	Tok string
	Pos int
	Err error
}

//errxgen: message="boom"
type Plain struct{}
`
	if err := os.WriteFile(filepath.Join(dir, "demo.go"), []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := run(dir); err != nil {
		t.Fatalf("run: %v", err)
	}
	out, err := os.ReadFile(filepath.Join(dir, "demo_errxgen.go"))
	if err != nil {
		t.Fatalf("generated file missing: %v", err)
	}
	g := string(out)
	for _, want := range []string{
		"// Code generated by errxgen; DO NOT EDIT.",
		"package demo",
		`fmt.Sprintf("bad token %q at %d", e.Tok, e.Pos)`,
		`func (e *LexError) Code() string { return "LEX" }`,
		`func (e *LexError) Unwrap() error { return e.Err }`,
		`func (e *Plain) Error() string {`,
		`return "boom"`,
	} {
		if !strings.Contains(g, want) {
			t.Fatalf("generated code missing %q in:\n%s", want, g)
		}
	}
	// No args + no code/unwrap → only Error(), constant string (no fmt args).
	if strings.Contains(g, `func (e *Plain) Code()`) {
		t.Fatal("Plain should not get a Code() method")
	}
}

func TestRunNoDirectivesNoFile(t *testing.T) {
	dir := t.TempDir()
	_ = os.WriteFile(filepath.Join(dir, "x.go"), []byte("package x\ntype T struct{}\n"), 0o644)
	if err := run(dir); err != nil {
		t.Fatalf("run: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "x_errxgen.go")); !os.IsNotExist(err) {
		t.Fatal("no directives should produce no generated file")
	}
}
